"""initial_schema_tables

Revision ID: e3ecafc8f8b3
Revises: 
Create Date: 2026-10-07 09:22:10.531514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ecafc8f8b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index(op.f('ix_otp_codes_identifier'), 'otp_codes', ['identifier'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('strike_count', sa.Integer(), nullable=False),
    sa.Column('reporting_suspended_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_locale', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_name', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('cruelty_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('nearest_police_station_name', sa.String(length=255), nullable=True),
    sa.Column('nearest_police_station_address', sa.Text(), nullable=True),
    sa.Column('nearest_police_station_phone', sa.String(length=32), nullable=True),
    sa.Column('complaint_pdf_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_cruelty_reports_reporter_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_cruelty_reports_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cruelty_reports'))
    )
    op.create_index(op.f('ix_cruelty_reports_category'), 'cruelty_reports', ['category'], unique=False)
    op.create_index(op.f('ix_cruelty_reports_latitude'), 'cruelty_reports', ['latitude'], unique=False)
    op.create_index(op.f('ix_cruelty_reports_longitude'), 'cruelty_reports', ['longitude'], unique=False)
    op.create_index(op.f('ix_cruelty_reports_reporter_id'), 'cruelty_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_cruelty_reports_status'), 'cruelty_reports', ['status'], unique=False)
    op.create_table('fund_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_inr', sa.Float(), nullable=False),
    sa.Column('allocation_date', sa.Date(), nullable=False),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('verified_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_fund_allocations_verified_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fund_allocations'))
    )
    op.create_index(op.f('ix_fund_allocations_allocation_date'), 'fund_allocations', ['allocation_date'], unique=False)
    op.create_index(op.f('ix_fund_allocations_category'), 'fund_allocations', ['category'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('primary_color', sa.String(length=64), nullable=True),
    sa.Column('secondary_color', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('microchip_id', sa.String(length=64), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_pets_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pets'))
    )
    op.create_index(op.f('ix_pets_microchip_id'), 'pets', ['microchip_id'], unique=False)
    op.create_index(op.f('ix_pets_owner_id'), 'pets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pets_species'), 'pets', ['species'], unique=False)
    op.create_table('strikes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('issued_by_id', sa.String(length=36), nullable=True),
    sa.Column('strike_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_strikes_issued_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strikes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strikes'))
    )
    op.create_index(op.f('ix_strikes_user_id'), 'strikes', ['user_id'], unique=False)
    op.create_table('vet_hospitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('emergency_phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_24x7', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ambulance_available', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_ratings', sa.Integer(), nullable=False),
    sa.Column('operating_hours', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vet_hospitals_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vet_hospitals'))
    )
    op.create_index(op.f('ix_vet_hospitals_is_active'), 'vet_hospitals', ['is_active'], unique=False)
    op.create_index(op.f('ix_vet_hospitals_is_verified'), 'vet_hospitals', ['is_verified'], unique=False)
    op.create_index(op.f('ix_vet_hospitals_latitude'), 'vet_hospitals', ['latitude'], unique=False)
    op.create_index(op.f('ix_vet_hospitals_longitude'), 'vet_hospitals', ['longitude'], unique=False)
    op.create_index(op.f('ix_vet_hospitals_name'), 'vet_hospitals', ['name'], unique=False)
    op.create_index(op.f('ix_vet_hospitals_place_id'), 'vet_hospitals', ['place_id'], unique=False)
    op.create_index(op.f('ix_vet_hospitals_user_id'), 'vet_hospitals', ['user_id'], unique=False)
    op.create_table('accident_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('reporter_phone', sa.String(length=20), nullable=True),
    sa.Column('animal_type', sa.String(length=64), nullable=False),
    sa.Column('condition_description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('accepted_hospital_id', sa.String(length=36), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_hospital_id'], ['vet_hospitals.id'], name=op.f('fk_accident_alerts_accepted_hospital_id_vet_hospitals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_accident_alerts_reporter_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accident_alerts'))
    )
    op.create_index(op.f('ix_accident_alerts_accepted_hospital_id'), 'accident_alerts', ['accepted_hospital_id'], unique=False)
    op.create_index(op.f('ix_accident_alerts_latitude'), 'accident_alerts', ['latitude'], unique=False)
    op.create_index(op.f('ix_accident_alerts_longitude'), 'accident_alerts', ['longitude'], unique=False)
    op.create_index(op.f('ix_accident_alerts_reporter_id'), 'accident_alerts', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_accident_alerts_status'), 'accident_alerts', ['status'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_amount_inr', sa.Float(), nullable=False),
    sa.Column('raised_amount_inr', sa.Float(), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['vet_hospitals.id'], name=op.f('fk_campaigns_hospital_id_vet_hospitals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_slug'), 'campaigns', ['slug'], unique=True)
    op.create_table('lost_found_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=True),
    sa.Column('post_type', sa.String(length=16), nullable=False),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('primary_color', sa.String(length=64), nullable=True),
    sa.Column('secondary_color', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('distinctive_marks', sa.Text(), nullable=True),
    sa.Column('collar_info', sa.Text(), nullable=True),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('photo_urls', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('masked_contact_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_lost_found_posts_pet_id_pets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lost_found_posts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lost_found_posts'))
    )
    op.create_index(op.f('ix_lost_found_posts_latitude'), 'lost_found_posts', ['latitude'], unique=False)
    op.create_index(op.f('ix_lost_found_posts_longitude'), 'lost_found_posts', ['longitude'], unique=False)
    op.create_index(op.f('ix_lost_found_posts_post_type'), 'lost_found_posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_lost_found_posts_species'), 'lost_found_posts', ['species'], unique=False)
    op.create_index(op.f('ix_lost_found_posts_status'), 'lost_found_posts', ['status'], unique=False)
    op.create_index(op.f('ix_lost_found_posts_user_id'), 'lost_found_posts', ['user_id'], unique=False)
    op.create_table('report_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('virus_scan_status', sa.String(length=32), nullable=False),
    sa.Column('exif_stripped', sa.Boolean(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['cruelty_reports.id'], name=op.f('fk_report_media_report_id_cruelty_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_media'))
    )
    op.create_index(op.f('ix_report_media_report_id'), 'report_media', ['report_id'], unique=False)
    op.create_table('alert_dispatches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('escalation_round', sa.Integer(), nullable=False),
    sa.Column('secure_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['accident_alerts.id'], name=op.f('fk_alert_dispatches_alert_id_accident_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['vet_hospitals.id'], name=op.f('fk_alert_dispatches_hospital_id_vet_hospitals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_dispatches'))
    )
    op.create_index(op.f('ix_alert_dispatches_alert_id'), 'alert_dispatches', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_dispatches_hospital_id'), 'alert_dispatches', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_alert_dispatches_secure_token'), 'alert_dispatches', ['secure_token'], unique=True)
    op.create_index(op.f('ix_alert_dispatches_status'), 'alert_dispatches', ['status'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('amount_inr', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('donor_name', sa.String(length=120), nullable=False),
    sa.Column('donor_email', sa.String(length=255), nullable=False),
    sa.Column('donor_phone', sa.String(length=20), nullable=True),
    sa.Column('donor_pan', sa.String(length=10), nullable=True),
    sa.Column('donor_address', sa.Text(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('receipt_number', sa.String(length=64), nullable=True),
    sa.Column('receipt_pdf_url', sa.Text(), nullable=True),
    sa.Column('tax_exemption_80g_issued', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_donations_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_donations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donations'))
    )
    op.create_index(op.f('ix_donations_campaign_id'), 'donations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_donations_donor_pan'), 'donations', ['donor_pan'], unique=False)
    op.create_index(op.f('ix_donations_payment_status'), 'donations', ['payment_status'], unique=False)
    op.create_index(op.f('ix_donations_razorpay_order_id'), 'donations', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_donations_razorpay_payment_id'), 'donations', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_donations_receipt_number'), 'donations', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_donations_user_id'), 'donations', ['user_id'], unique=False)
    op.create_table('pet_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('vector_data', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['lost_found_posts.id'], name=op.f('fk_pet_embeddings_post_id_lost_found_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_embeddings'))
    )
    op.create_index(op.f('ix_pet_embeddings_post_id'), 'pet_embeddings', ['post_id'], unique=False)
    op.create_table('pet_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lost_post_id', sa.String(length=36), nullable=False),
    sa.Column('found_post_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['found_post_id'], ['lost_found_posts.id'], name=op.f('fk_pet_matches_found_post_id_lost_found_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_post_id'], ['lost_found_posts.id'], name=op.f('fk_pet_matches_lost_post_id_lost_found_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet_matches'))
    )
    op.create_index(op.f('ix_pet_matches_found_post_id'), 'pet_matches', ['found_post_id'], unique=False)
    op.create_index(op.f('ix_pet_matches_lost_post_id'), 'pet_matches', ['lost_post_id'], unique=False)
    op.create_index(op.f('ix_pet_matches_similarity_score'), 'pet_matches', ['similarity_score'], unique=False)
    op.create_index(op.f('ix_pet_matches_status'), 'pet_matches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pet_matches_status'), table_name='pet_matches')
    op.drop_index(op.f('ix_pet_matches_similarity_score'), table_name='pet_matches')
    op.drop_index(op.f('ix_pet_matches_lost_post_id'), table_name='pet_matches')
    op.drop_index(op.f('ix_pet_matches_found_post_id'), table_name='pet_matches')
    op.drop_table('pet_matches')
    op.drop_index(op.f('ix_pet_embeddings_post_id'), table_name='pet_embeddings')
    op.drop_table('pet_embeddings')
    op.drop_index(op.f('ix_donations_user_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_receipt_number'), table_name='donations')
    op.drop_index(op.f('ix_donations_razorpay_payment_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_razorpay_order_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_payment_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_pan'), table_name='donations')
    op.drop_index(op.f('ix_donations_campaign_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_alert_dispatches_status'), table_name='alert_dispatches')
    op.drop_index(op.f('ix_alert_dispatches_secure_token'), table_name='alert_dispatches')
    op.drop_index(op.f('ix_alert_dispatches_hospital_id'), table_name='alert_dispatches')
    op.drop_index(op.f('ix_alert_dispatches_alert_id'), table_name='alert_dispatches')
    op.drop_table('alert_dispatches')
    op.drop_index(op.f('ix_report_media_report_id'), table_name='report_media')
    op.drop_table('report_media')
    op.drop_index(op.f('ix_lost_found_posts_user_id'), table_name='lost_found_posts')
    op.drop_index(op.f('ix_lost_found_posts_status'), table_name='lost_found_posts')
    op.drop_index(op.f('ix_lost_found_posts_species'), table_name='lost_found_posts')
    op.drop_index(op.f('ix_lost_found_posts_post_type'), table_name='lost_found_posts')
    op.drop_index(op.f('ix_lost_found_posts_longitude'), table_name='lost_found_posts')
    op.drop_index(op.f('ix_lost_found_posts_latitude'), table_name='lost_found_posts')
    op.drop_table('lost_found_posts')
    op.drop_index(op.f('ix_campaigns_slug'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_accident_alerts_status'), table_name='accident_alerts')
    op.drop_index(op.f('ix_accident_alerts_reporter_id'), table_name='accident_alerts')
    op.drop_index(op.f('ix_accident_alerts_longitude'), table_name='accident_alerts')
    op.drop_index(op.f('ix_accident_alerts_latitude'), table_name='accident_alerts')
    op.drop_index(op.f('ix_accident_alerts_accepted_hospital_id'), table_name='accident_alerts')
    op.drop_table('accident_alerts')
    op.drop_index(op.f('ix_vet_hospitals_user_id'), table_name='vet_hospitals')
    op.drop_index(op.f('ix_vet_hospitals_place_id'), table_name='vet_hospitals')
    op.drop_index(op.f('ix_vet_hospitals_name'), table_name='vet_hospitals')
    op.drop_index(op.f('ix_vet_hospitals_longitude'), table_name='vet_hospitals')
    op.drop_index(op.f('ix_vet_hospitals_latitude'), table_name='vet_hospitals')
    op.drop_index(op.f('ix_vet_hospitals_is_verified'), table_name='vet_hospitals')
    op.drop_index(op.f('ix_vet_hospitals_is_active'), table_name='vet_hospitals')
    op.drop_table('vet_hospitals')
    op.drop_index(op.f('ix_strikes_user_id'), table_name='strikes')
    op.drop_table('strikes')
    op.drop_index(op.f('ix_pets_species'), table_name='pets')
    op.drop_index(op.f('ix_pets_owner_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_microchip_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fund_allocations_category'), table_name='fund_allocations')
    op.drop_index(op.f('ix_fund_allocations_allocation_date'), table_name='fund_allocations')
    op.drop_table('fund_allocations')
    op.drop_index(op.f('ix_cruelty_reports_status'), table_name='cruelty_reports')
    op.drop_index(op.f('ix_cruelty_reports_reporter_id'), table_name='cruelty_reports')
    op.drop_index(op.f('ix_cruelty_reports_longitude'), table_name='cruelty_reports')
    op.drop_index(op.f('ix_cruelty_reports_latitude'), table_name='cruelty_reports')
    op.drop_index(op.f('ix_cruelty_reports_category'), table_name='cruelty_reports')
    op.drop_table('cruelty_reports')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_otp_codes_identifier'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
